[book]
authors = ["Tanat"]
language = "en"
multilingual = false
src = "src"
title = "PettySync Report"
description = "PettySync's online report."

[output.html]
mathjax-support = true
default-theme = "light"
preferred-dark-theme = "light"